version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout:
          path: igseq
      - restore_cache:
          keys:
            - cache-{{ checksum "igseq/igseq/data/environment.yml" }}
      - run:
          name: Install
          command: |
            if [[ ! -e ~/miniconda3/envs/igseq ]]; then
              wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
              bash Miniconda3-latest-Linux-x86_64.sh -b
              ~/miniconda3/bin/conda install -c conda-forge mamba --quiet
              ~/miniconda3/bin/mamba env update --file igseq/igseq/data/environment.yml --quiet
            fi
          no_output_timeout: 20m
      - save_cache:
          paths: [ ~/miniconda3 ]
          key: cache-{{ checksum "igseq/igseq/data/environment.yml" }}
      - run:
          name: Store conda env shell environment
          command: |
            source ~/miniconda3/bin/activate igseq
            env | tee /tmp/env.txt
      - run:
          name: Test python package
          command: |
            cd igseq
            source ~/miniconda3/bin/activate igseq
            TEST_IGSEQ_LIVE=no python -m unittest -v
      - run:
          name: Test example scripts
          command: |
            cd igseq
            source ~/miniconda3/bin/activate igseq
            SKIPBCL2FASTQ=yes tools/check-examples.sh
      - store_artifacts:
          path: /tmp/igseq-testdirs
          destination: igseq-testdirs
      - store_artifacts:
          path: /tmp/env.txt
          destination: environment
