version: 2.1
jobs:
  build:
    machine:
      image: default
    steps:
      - checkout:
          path: igseq
      - restore_cache:
          keys:
            - cache-{{ checksum "igseq/igseq/data/environment.yml" }}
      - run:
          name: Install Conda Environment
          command: |
            if [[ ! -e ~/miniconda3/envs/igseq ]]; then
              wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
              bash Miniconda3-latest-Linux-x86_64.sh -b
              ~/miniconda3/bin/conda install -c conda-forge mamba --quiet
              ~/miniconda3/bin/mamba env update --file igseq/igseq/data/environment.yml --quiet
            fi
          no_output_timeout: 20m
      - save_cache:
          paths: [ ~/miniconda3 ]
          key: cache-{{ checksum "igseq/igseq/data/environment.yml" }}
      - run:
          name: Store conda env shell environment
          command: |
            source ~/miniconda3/bin/activate igseq
            env | tee /tmp/env.txt
      - run:
          name: Store conda env package list
          command: |
            source ~/miniconda3/bin/activate igseq
            conda list --explicit | tee /tmp/packages.txt
      - run:
          name: Test python package
          command: |
            cd igseq
            source ~/miniconda3/bin/activate igseq
            TEST_IGSEQ_LIVE=yes python -m unittest -v
      - run:
          name: Install python package
          command: |
            cd igseq
            source ~/miniconda3/bin/activate igseq
            pip install .
            igseq -h
      - run:
          name: Test example scripts
          command: |
            cd igseq
            source ~/miniconda3/bin/activate igseq
            SKIPBCL2FASTQ=yes tools/check-examples.sh
      - store_artifacts:
          name: "Store Artifacts: shell environment"
          path: /tmp/env.txt
          destination: environment
      - store_artifacts:
          name: "Store Artifacts: conda packages"
          path: /tmp/packages.txt
          destination: packages
      - store_artifacts:
          name: "Store Artifacts: igseq-testdirs"
          path: /tmp/igseq-testdirs
          destination: igseq-testdirs
